"""Expert bit allocation case study visualization.

This module reads the JSON files generated by `logs/allocation_case_study.py`
and creates intuitive visualizations comparing the three bit allocation
strategies:

    - Expert-Fixed: Each expert uses the same fixed bit schedule
    - Global-Fixed: Globally-ranked, but still using fixed number of high bits
    - Global-BPW: Global dynamic programming allocation under bpw constraint

Usage
-----
    python -m viz.allocation_case_study                    # all models (PNG)
    python -m viz.allocation_case_study --model dsv1      # one model (PNG)
    python -m viz.allocation_case_study --pdf             # save as PDF
    python -m viz.allocation_case_study --svg             # save as SVG
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
from matplotlib.patches import Rectangle

# Make sibling modules importable when run as a script.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUT_ROOT = "plot/allocation_case_study"
DATA_ROOT = "logs/allocation_case_study"

# Original color scheme (commented out):
# BIT_COLORS = [
#     (0.85, 0.85, 0.85),   # 0-bit: light gray
#     (1.00, 0.87, 0.47),   # 1-bit: #FFDF79
#     (0.96, 0.78, 0.68),   # 2-bit: #F6C6AD
#     (0.90, 0.50, 0.15),   # 3-bit: orange
#     (0.85, 0.20, 0.25),   # 4-bit: red
# ]
# BIT_COLORS = [
#     (0.85, 0.85, 0.85),   # 0-bit: light gray
#     (0.55, 0.72, 0.90),   # 1-bit: light blue
#     (0.20, 0.65, 0.35),   # 2-bit: green
#     (0.90, 0.50, 0.15),   # 3-bit: orange
#     (0.31, 0.65, 0.18),   # 4-bit: #4EA72E
# ]
BIT_COLORS = [
    (0.95, 0.95, 0.95),   # 0-bit: very light gray
    (0.84, 0.96, 0.69),   # 1-bit: #D7F5B1
    (0.62, 0.89, 0.81),   # 2-bit: #9EE2CF
    (1.00, 0.75, 0.00),   # 3-bit: #FFC000
    (0.97, 0.55, 0.49),   # 4-bit: #F78D7C
]
BIT_CMAP = ListedColormap(BIT_COLORS, name="bitwidth")


def apply_paper_style():
    """Tighter, paper-friendly matplotlib defaults."""
    import matplotlib as mpl
    mpl.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "legend.fontsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "axes.grid": False,
        "grid.alpha": 0.3,
        "figure.dpi": 130,
        "savefig.dpi": 220,
        "savefig.bbox": "tight",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        # SVG settings for better PPT compatibility
        "svg.fonttype": "none",  # Keep text as text, not convert to paths
    })


@dataclass
class AllocationData:
    """Parsed allocation data for one case study."""
    case_name: str
    model_id: str
    model_label: str
    target_bpw: float
    flat_layer: int
    skew_layer: int
    # layer_type -> method_name -> (matrix, stats)
    layers: Dict[str, Dict[str, Tuple[np.ndarray, dict]]]


def load_json_case(json_path: str) -> Optional[AllocationData]:
    """Load and parse one allocation case study JSON file."""
    with open(json_path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    case = payload["case"]
    layers_payload = payload["layers"]

    layers = {}
    for layer_type in ("flat", "skew"):
        layer_data = layers_payload.get(layer_type)
        if layer_data is None:
            continue
        methods = {}
        for method_name in ("Expert-Fixed", "Global-Fixed", "Global-BPW"):
            method_data = layer_data["methods"].get(method_name)
            if method_data is None:
                continue
            matrix = np.asarray(method_data["matrix"], dtype=int)
            stats = method_data["stats"]
            methods[method_name] = (matrix, stats)
        layers[layer_type] = methods

    if not layers:
        return None

    return AllocationData(
        case_name=case["name"],
        model_id=case["model_id"],
        model_label=case["model_label"],
        target_bpw=case["target_bpw"],
        flat_layer=case["flat_layer"],
        skew_layer=case["skew_layer"],
        layers=layers,
    )


def discover_json_cases(data_dir: str = DATA_ROOT) -> List[str]:
    """Find all JSON case study files in the data directory."""
    if not os.path.isdir(data_dir):
        return []
    jsons = []
    for fn in os.listdir(data_dir):
        if fn.endswith(".json") and not fn.startswith("_"):
            jsons.append(os.path.join(data_dir, fn))
    return sorted(jsons)


def plot_single_panel(ax, matrix: np.ndarray, stats: dict, method_name: str) -> None:
    """Plot a single allocation panel with spaced squares."""
    n_experts, n_slices = matrix.shape

    # Gap between squares (relative to square size)
    gap = 0.15

    # Set axes limits with extra margin to avoid clipping
    margin = 0.6
    ax.set_xlim(-margin, n_slices - 1 + margin)
    ax.set_ylim(n_experts - 1 + margin, -margin)  # Reverse y-axis for imshow-like orientation

    # Square size = 1 - gap on each side
    square_size = 1.0 - 2 * gap

    # Draw each square
    for i in range(n_experts):
        for j in range(n_slices):
            bit_value = matrix[i, j]
            color = BIT_COLORS[bit_value]
            rect = Rectangle(
                (j - square_size / 2, i - square_size / 2),
                square_size,
                square_size,
                facecolor=color,
                edgecolor='none'
            )
            ax.add_patch(rect)

    # Clean ticks - only show some for readability
    expert_ticks = [0, n_experts // 2, n_experts - 1] if n_experts > 1 else [0]
    ax.set_yticks(expert_ticks)
    ax.set_yticklabels([str(t) for t in expert_ticks])

    slice_ticks = [0, n_slices - 1] if n_slices > 1 else [0]
    ax.set_xticks(slice_ticks)
    ax.set_xticklabels([str(t) for t in slice_ticks])

    # Stats annotation - place BELOW the plot
    counts = stats.get("counts", {})
    c0 = counts.get("0", 0)
    c1 = counts.get("1", 0)
    c2 = counts.get("2", 0)
    c3 = counts.get("3", 0)
    c4 = counts.get("4", 0)

    stats_line1 = f"0bit:{c0} | 1bit:{c1} | 2bit:{c2}"
    stats_line2 = f"3bit:{c3} | 4bit:{c4}"
    stats_text = f"{stats_line1}\n{stats_line2}"

    ax.text(
        0.5, -0.10, stats_text,
        transform=ax.transAxes,
        fontsize=7,
        verticalalignment="top",
        horizontalalignment="center",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.2, pad=1, linewidth=0.5),
    )

    ax.set_title(method_name, fontsize=9, fontweight="bold", pad=6)

    # Make axes spines semi-transparent
    for spine in ax.spines.values():
        spine.set_alpha(0.3)

    # Return a dummy im object for colorbar compatibility
    dummy_im = ax.imshow([[0]], cmap=BIT_CMAP, vmin=0, vmax=4, visible=False)
    return dummy_im


def plot_allocation_comparison(
    data: AllocationData,
    out_dir: str = OUT_ROOT,
    use_pdf: bool = False,
    use_svg: bool = False,
) -> str:
    """Main visualization: 1 row × 6 columns (3 flat + 3 skew)."""
    fig = plt.figure(figsize=(16, 7))

    # 6 panels in one row: [flat ×3, skew ×3] + colorbar
    gs = fig.add_gridspec(1, 7, width_ratios=[1, 1, 1, 0.05, 1, 1, 1], wspace=0.18)

    methods = ["Expert-Fixed", "Global-Fixed", "Global-BPW"]

    axes_list = []

    # Plot all panels
    im = None
    # First 3 panels: Flat layer
    layer_type, layer_idx = "flat", data.flat_layer
    layer_data = data.layers.get(layer_type, {})
    for col, method in enumerate(methods):
        ax = fig.add_subplot(gs[0, col])
        axes_list.append(ax)
        matrix, stats = layer_data.get(method, (None, None))
        if matrix is None:
            ax.text(0.5, 0.5, "no data", ha="center", va="center")
            continue
        im = plot_single_panel(ax, matrix, stats, method)

        # Labels only for first panel
        if col == 0:
            ax.set_ylabel(f"Expert", fontsize=8, labelpad=4)
        else:
            ax.set_ylabel("")
        ax.set_xlabel("Slice", fontsize=7, labelpad=2)

    # Last 3 panels: Skew layer
    layer_type, layer_idx = "skew", data.skew_layer
    layer_data = data.layers.get(layer_type, {})
    for col, method in enumerate(methods):
        ax = fig.add_subplot(gs[0, col + 4])  # skip the divider column
        axes_list.append(ax)
        matrix, stats = layer_data.get(method, (None, None))
        if matrix is None:
            ax.text(0.5, 0.5, "no data", ha="center", va="center")
            continue
        plot_single_panel(ax, matrix, stats, method)

        # Labels
        ax.set_ylabel("")
        ax.set_xlabel("Slice", fontsize=7, labelpad=2)

    # Add section headers
    fig.text(0.25, 0.992, f"Flat Layer (L{data.flat_layer})",
             ha="center", va="top", fontsize=11, fontweight="bold", color="#333333")
    fig.text(0.75, 0.992, f"Skew Layer (L{data.skew_layer})",
             ha="center", va="top", fontsize=11, fontweight="bold", color="#333333")

    # Add vertical divider between flat and skew - 高度减少一半
    divider = fig.add_subplot(gs[0, 3])
    divider.axis('off')
    divider.axvline(0.5, ymin=0.25, ymax=0.75, color='#999999', linewidth=1.5, linestyle='-')

    # Colorbar - 缩小到1/4
    cbar_ax = fig.add_axes([0.92, 0.4, 0.008, 0.2])  # [left, bottom, width, height]
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.set_ticks([0, 1, 2, 3, 4])
    cbar.set_ticklabels(["0-bit", "1-bit", "2-bit", "3-bit", "4-bit"], fontsize=5)
    cbar.set_label("Bit Width", fontsize=6, labelpad=4)
    cbar.ax.tick_params(labelsize=5, length=2, pad=1)
    # Remove colorbar frame
    cbar.outline.set_visible(False)
    # Remove colorbar frame
    cbar.outline.set_visible(False)

    # Main title
    fig.suptitle(
        f"Expert Bit Allocation Comparison — {data.model_label}\n"
        f"Target: {data.target_bpw:.1f} bpw",
        fontsize=12,
        y=0.998,
    )

    # Force same aspect ratio on all axes
    for ax in axes_list:
        ax.set_aspect(0.4)

    os.makedirs(out_dir, exist_ok=True)
    if use_svg:
        ext = "svg"
    elif use_pdf:
        ext = "pdf"
    else:
        ext = "png"
    fp = os.path.join(out_dir, f"allocation_{data.case_name}.{ext}")
    if use_svg:
        # Save SVG with text kept as text for better PPT compatibility
        plt.savefig(fp, format='svg', bbox_inches='tight')
    else:
        plt.savefig(fp)
    plt.close(fig)
    print(f"[plot_allocation_comparison] saved {fp}")
    return fp


def main():
    apply_paper_style()
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default=DATA_ROOT,
                        help="directory with allocation JSON files")
    parser.add_argument("--model", default=None,
                        help="only process one model (dsv1, dsv2, qwen3, etc.)")
    parser.add_argument("--pdf", action="store_true",
                        help="save as PDF instead of PNG")
    parser.add_argument("--svg", action="store_true",
                        help="save as SVG instead of PNG")
    args = parser.parse_args()

    json_paths = discover_json_cases(args.data_dir)
    if not json_paths:
        print(f"[allocation_case_study] no JSON files found in {args.data_dir}")
        return

    # Filter by model if requested
    if args.model:
        filtered = []
        for p in json_paths:
            if args.model.lower() in p.lower():
                filtered.append(p)
        json_paths = filtered
        if not json_paths:
            print(f"[allocation_case_study] no JSON files matched model '{args.model}'")
            return

    # Load all data first
    all_data = []
    for json_path in json_paths:
        data = load_json_case(json_path)
        if data is not None:
            all_data.append(data)
            print(f"[allocation_case_study] loaded {data.model_label} from {json_path}")

    if not all_data:
        print("[allocation_case_study] no valid data loaded")
        return

    # Generate visualizations per case
    for data in all_data:
        print(f"\n=== Processing {data.model_label} ===")
        plot_allocation_comparison(data, use_pdf=args.pdf, use_svg=args.svg)


if __name__ == "__main__":
    main()
